apiVersion: v1
kind: Service
metadata:
   labels:
     app: bootcamp
     role: web
     tier: frontend
   name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bootcamp
    role: web
    tier: frontend
  type: LoadBalancer
