# use this with `docker-compose up` against a generic Docker end-point (e.g. standalone Docker)
version: "3.7"

services:
  
  frontend:
    image: codydearkland/cmbu-app-frontend:latest 
    depends_on:
      - pyapi
    ports:
      - 80:80
    networks:
      - cmbu-network

  pyapi:
    image: codydearkland/cmbu-app-backend:latest
    depends_on: 
      - db
    networks:
      - cmbu-network

  db: 
    image: codydearkland/cmbu-db-app:latest
    environment:
      POSTGRES_USER: postgres
    networks:
      - cmbu-network


networks:
  cmbu-network:
    driver: bridge # a user defined bridge is required; the default bridge network doesn't support name resolution
